"""initial-migration

Revision ID: 244b069f0599
Revises: 
Create Date: 2023-03-29 11:39:26.074622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244b069f0599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('made_by', sa.String(length=250), nullable=True),
    sa.Column('menu_item', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=10), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('made_at', sa.DateTime(), nullable=True),
    sa.Column('needed_by', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=9), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['made_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_item'], ['Menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    op.drop_table('orders')
    # ### end Alembic commands ###
