"""menu controller

Revision ID: 3c7a21f9d677
Revises: 10be8b28e445
Create Date: 2023-03-29 16:52:07.781318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7a21f9d677'
down_revision = '10be8b28e445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('Menu', schema=None) as batch_op:
        batch_op.drop_column('reg_by')

    # ### end Alembic commands ###
