"""food_categories

Revision ID: 5ea810682787
Revises: dfeebba2ca6f
Create Date: 2023-03-28 11:52:49.439524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea810682787'
down_revision = 'dfeebba2ca6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Food_Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.String(length=250), nullable=True),
    sa.Column('updated_at', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Food_Categories')
    # ### end Alembic commands ###
