"""initial migration

Revision ID: 6c4b19196a30
Revises: 
Create Date: 2023-03-28 15:13:42.386783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4b19196a30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Food_Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('in_category', sa.Integer(), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.String(length=250), nullable=True),
    sa.Column('updated_at', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['in_category'], ['Food_Categories.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Food_Items')
    # ### end Alembic commands ###
