"""initial-migration

Revision ID: be374fe06a29
Revises: 
Create Date: 2023-03-29 14:57:30.361262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be374fe06a29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Menu', schema=None) as batch_op:
        batch_op.drop_column('upd_by')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_mode')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_mode', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('Menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upd_by', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
