"""controllers

Revision ID: d47ed81bc5d4
Revises: 3c7a21f9d677
Create Date: 2023-03-31 12:33:32.744523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47ed81bc5d4'
down_revision = '3c7a21f9d677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=True))
        batch_op.drop_column('reg_by')
        batch_op.drop_column('upd_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upd_by', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('reg_by', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('registered_by')

    # ### end Alembic commands ###
