"""orders

Revision ID: fbfe067f2d14
Revises: 6c4b19196a30
Create Date: 2023-03-28 16:38:10.016801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfe067f2d14'
down_revision = '6c4b19196a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('price_unit', sa.String(length=3), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('served_at', sa.String(length=255), nullable=True),
    sa.Column('upd_by', sa.String(length=50), nullable=True),
    sa.Column('reg_at', sa.DateTime(), nullable=True),
    sa.Column('upd_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Food_Categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Food_Categories', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('Food_Items', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('Gallery', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('registered_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('Gallery', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('registered_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('Food_Items', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('registered_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('Food_Categories', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('registered_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    op.drop_table('Menu')
    # ### end Alembic commands ###
